### PR TITLE
Update golang.org/x/sys.

### PR DESCRIPTION
**Pull request by tjni**
This fixes the build on Darwin using Go 1.18.

See https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus

### CODE REVIEW

**Comment by tjni** [comment]
I updated the PR so that it can be merged into master.

**Comment by tjni** [comment]
Hi @aaronjanse, do you have time to merge this (and potentially releasing a new version)? I'd appreciate it as it would let me clean up my fork as well as simplify the [packaging in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/3mux/default.nix).

**Comment by aaronjanse** [comment]
Sorry about not responding! I'll take a look tonight

**Review by aaronjanse — APPROVED** [review]

**Comment by aaronjanse** [comment]
Thank you @tjni!

**Comment by tjni** [comment]
Thank you!

**Pull request merged**
